
from NL2PLN.simple_puzzle_manager import SimpleProofHandler
from NL2PLN.metta.mettalog_handler import MettalogHandler

reasoning="I need to convert the given natural language text about Sarah's science fair experiment into PLN format. The text contains multiple factual statements about an experiment design, methodology, and results, followed by a question asking about the experimental design, results, and conclusion. I'll break down the complex narrative into atomic logical components: Sarah's project topic, her experimental setup (three groups of plants with different music conditions), the controlled variables (lighting, temperature, watering schedule), the measurements taken, the results for each group, the teacher's reaction, and Sarah's conclusion. For the question, I'll create a PLN query that can retrieve the experimental design, results, and conclusion information. I'll use predicates to represent relationships like ExperimentTopic, PlantGroup, MusicCondition, WateringSchedule, MeasurementProtocol, GroupResult, TeacherReaction, and ExperimentConclusion."
typedefs=['(: ExperimentTopic (-> (: $person Object) (: $topic Object) Type))', '(: PlantGroup (-> (: $experiment Object) (: $group Object) Type))', '(: MusicCondition (-> (: $group Object) (: $music_type Object) Type))', '(: MusicDuration (-> (: $group Object) (: $duration Object) Type))', '(: ControlledVariable (-> (: $experiment Object) (: $variable Object) Type))', '(: WateringSchedule (-> (: $experiment Object) (: $amount Object) (: $time Object) (: $frequency Object) Type))', '(: MeasurementProtocol (-> (: $experiment Object) (: $measurement Object) (: $frequency Object) Type))', '(: GroupResult (-> (: $group Object) (: $height Object) Type))', '(: TeacherReaction (-> (: $teacher Object) (: $experiment Object) (: $reaction Object) Type))', '(: ExperimentConclusion (-> (: $person Object) (: $conclusion Object) Type))', '(: ExperimentDuration (-> (: $experiment Object) (: $duration Object) Type))']
statements=['(: sarah_topic (WithTV (ExperimentTopic Sarah MusicEffectOnPlantGrowth) (STV 1.0 1.0)))', '(: group1_setup (WithTV (PlantGroup SarahExperiment ClassicalGroup) (STV 1.0 1.0)))', '(: group2_setup (WithTV (PlantGroup SarahExperiment RockGroup) (STV 1.0 1.0)))', '(: group3_setup (WithTV (PlantGroup SarahExperiment ControlGroup) (STV 1.0 1.0)))', '(: classical_condition (WithTV (MusicCondition ClassicalGroup ClassicalMusic) (STV 1.0 1.0)))', '(: rock_condition (WithTV (MusicCondition RockGroup RockMusic) (STV 1.0 1.0)))', '(: silence_condition (WithTV (MusicCondition ControlGroup Silence) (STV 1.0 1.0)))', '(: music_duration (WithTV (MusicDuration ClassicalGroup TwoHoursDaily) (STV 1.0 1.0)))', '(: rock_duration (WithTV (MusicDuration RockGroup TwoHoursDaily) (STV 1.0 1.0)))', '(: lighting_control (WithTV (ControlledVariable SarahExperiment ControlledLighting) (STV 1.0 1.0)))', '(: temperature_control (WithTV (ControlledVariable SarahExperiment ControlledTemperature) (STV 1.0 1.0)))', '(: watering_schedule (WithTV (WateringSchedule SarahExperiment FiftyML EightAM Daily) (STV 1.0 1.0)))', '(: measurement_protocol (WithTV (MeasurementProtocol SarahExperiment HeightMeasurement Weekly) (STV 1.0 1.0)))', '(: experiment_duration (WithTV (ExperimentDuration SarahExperiment FourWeeks) (STV 1.0 1.0)))', '(: classical_result (WithTV (GroupResult ClassicalGroup TwelveInches) (STV 1.0 1.0)))', '(: rock_result (WithTV (GroupResult RockGroup NineInches) (STV 1.0 1.0)))', '(: control_result (WithTV (GroupResult ControlGroup TenInches) (STV 1.0 1.0)))', '(: teacher_impressed (WithTV (TeacherReaction MrsJohnson SarahExperiment Impressed) (STV 1.0 1.0)))', '(: sarah_conclusion (WithTV (ExperimentConclusion Sarah ClassicalMusicPositiveEffect) (STV 1.0 1.0)))']
questions=['(: $query1 (WithTV (And (ExperimentTopic Sarah $topic) (PlantGroup SarahExperiment $group1) (PlantGroup SarahExperiment $group2) (PlantGroup SarahExperiment $group3) (MusicCondition $group1 $music1) (MusicCondition $group2 $music2) (MusicCondition $group3 $music3) (WateringSchedule SarahExperiment $amount $time $frequency)) $tv))', '(: $query2 (WithTV (And (GroupResult ClassicalGroup $result1) (GroupResult RockGroup $result2) (GroupResult ControlGroup $result3) (ExperimentConclusion Sarah $conclusion)) $tv))']

pln_data = {
    'statements': statements,
    'questions': questions
}

print(pln_data['questions'])

#metta_handler = MettalogHandler()
#proof_handler = SimpleProofHandler(metta_handler)

#proof_handler.try_to_proof(pln_data,0)
